services:
    sniper.fontawesome.listener:
        class: sniper\fontawesome\event\listener
        arguments:
            - '@user'
            - '@template'
            - '@auth'
            - '@config'
        tags:
            - { name: event.listener }
